export const MenuItems=[
    {title:'HOME',
    url:'#',
    cName:'nav-links'
},
{title:'SERVICES',
    url:'#',
    cName:'nav-links'
},
{title:'BLOG',
    url:'#',
    cName:'nav-links'
},
{title:'PORTFOLIO',
    url:'#',
    cName:'nav-links'
},
{title:'CONTACT',
    url:'#',
    cName:'nav-links'
},
]
